name: Homework15
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  run-action:
    name: Run action
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js instead16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: "npm"
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci
        
      - name: Eslint
        run: npm run eslint

      - name: Build
        run: npm run build
